#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MPMS_DB")]
	public partial class LINQDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    partial void InsertShops(Shops instance);
    partial void UpdateShops(Shops instance);
    partial void DeleteShops(Shops instance);
    partial void InsertCardLevels(CardLevels instance);
    partial void UpdateCardLevels(CardLevels instance);
    partial void DeleteCardLevels(CardLevels instance);
    partial void InsertCategories(Categories instance);
    partial void UpdateCategories(Categories instance);
    partial void DeleteCategories(Categories instance);
    partial void InsertConsumeOrders(ConsumeOrders instance);
    partial void UpdateConsumeOrders(ConsumeOrders instance);
    partial void DeleteConsumeOrders(ConsumeOrders instance);
    partial void InsertExchangGifts(ExchangGifts instance);
    partial void UpdateExchangGifts(ExchangGifts instance);
    partial void DeleteExchangGifts(ExchangGifts instance);
    partial void InsertExchangLogs(ExchangLogs instance);
    partial void UpdateExchangLogs(ExchangLogs instance);
    partial void DeleteExchangLogs(ExchangLogs instance);
    partial void InsertTransferLogs(TransferLogs instance);
    partial void UpdateTransferLogs(TransferLogs instance);
    partial void DeleteTransferLogs(TransferLogs instance);
    partial void InsertMemCards(MemCards instance);
    partial void UpdateMemCards(MemCards instance);
    partial void DeleteMemCards(MemCards instance);
    #endregion
		
		public LINQDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MPMSDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
		
		public System.Data.Linq.Table<Shops> Shops
		{
			get
			{
				return this.GetTable<Shops>();
			}
		}
		
		public System.Data.Linq.Table<CategoryItems> CategoryItems
		{
			get
			{
				return this.GetTable<CategoryItems>();
			}
		}
		
		public System.Data.Linq.Table<CardLevels> CardLevels
		{
			get
			{
				return this.GetTable<CardLevels>();
			}
		}
		
		public System.Data.Linq.Table<Categories> Categories
		{
			get
			{
				return this.GetTable<Categories>();
			}
		}
		
		public System.Data.Linq.Table<ConsumeOrders> ConsumeOrders
		{
			get
			{
				return this.GetTable<ConsumeOrders>();
			}
		}
		
		public System.Data.Linq.Table<ExchangGifts> ExchangGifts
		{
			get
			{
				return this.GetTable<ExchangGifts>();
			}
		}
		
		public System.Data.Linq.Table<ExchangLogs> ExchangLogs
		{
			get
			{
				return this.GetTable<ExchangLogs>();
			}
		}
		
		public System.Data.Linq.Table<TransferLogs> TransferLogs
		{
			get
			{
				return this.GetTable<TransferLogs>();
			}
		}
		
		public System.Data.Linq.Table<MemCards> MemCards
		{
			get
			{
				return this.GetTable<MemCards>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _U_ID;
		
		private System.Nullable<int> _S_ID;
		
		private string _U_LoginName;
		
		private string _U_Password;
		
		private string _U_RealName;
		
		private string _U_Sex;
		
		private string _U_Telephone;
		
		private System.Nullable<int> _U_Role;
		
		private System.Nullable<bool> _U_CanDelete;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnU_IDChanging(int value);
    partial void OnU_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnU_LoginNameChanging(string value);
    partial void OnU_LoginNameChanged();
    partial void OnU_PasswordChanging(string value);
    partial void OnU_PasswordChanged();
    partial void OnU_RealNameChanging(string value);
    partial void OnU_RealNameChanged();
    partial void OnU_SexChanging(string value);
    partial void OnU_SexChanged();
    partial void OnU_TelephoneChanging(string value);
    partial void OnU_TelephoneChanged();
    partial void OnU_RoleChanging(System.Nullable<int> value);
    partial void OnU_RoleChanged();
    partial void OnU_CanDeleteChanging(System.Nullable<bool> value);
    partial void OnU_CanDeleteChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int U_ID
		{
			get
			{
				return this._U_ID;
			}
			set
			{
				if ((this._U_ID != value))
				{
					this.OnU_IDChanging(value);
					this.SendPropertyChanging();
					this._U_ID = value;
					this.SendPropertyChanged("U_ID");
					this.OnU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_LoginName", DbType="NVarChar(20)")]
		public string U_LoginName
		{
			get
			{
				return this._U_LoginName;
			}
			set
			{
				if ((this._U_LoginName != value))
				{
					this.OnU_LoginNameChanging(value);
					this.SendPropertyChanging();
					this._U_LoginName = value;
					this.SendPropertyChanged("U_LoginName");
					this.OnU_LoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Password", DbType="NVarChar(20)")]
		public string U_Password
		{
			get
			{
				return this._U_Password;
			}
			set
			{
				if ((this._U_Password != value))
				{
					this.OnU_PasswordChanging(value);
					this.SendPropertyChanging();
					this._U_Password = value;
					this.SendPropertyChanged("U_Password");
					this.OnU_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_RealName", DbType="NVarChar(20)")]
		public string U_RealName
		{
			get
			{
				return this._U_RealName;
			}
			set
			{
				if ((this._U_RealName != value))
				{
					this.OnU_RealNameChanging(value);
					this.SendPropertyChanging();
					this._U_RealName = value;
					this.SendPropertyChanged("U_RealName");
					this.OnU_RealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Sex", DbType="NVarChar(20)")]
		public string U_Sex
		{
			get
			{
				return this._U_Sex;
			}
			set
			{
				if ((this._U_Sex != value))
				{
					this.OnU_SexChanging(value);
					this.SendPropertyChanging();
					this._U_Sex = value;
					this.SendPropertyChanged("U_Sex");
					this.OnU_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Telephone", DbType="NVarChar(20)")]
		public string U_Telephone
		{
			get
			{
				return this._U_Telephone;
			}
			set
			{
				if ((this._U_Telephone != value))
				{
					this.OnU_TelephoneChanging(value);
					this.SendPropertyChanging();
					this._U_Telephone = value;
					this.SendPropertyChanged("U_Telephone");
					this.OnU_TelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Role", DbType="Int")]
		public System.Nullable<int> U_Role
		{
			get
			{
				return this._U_Role;
			}
			set
			{
				if ((this._U_Role != value))
				{
					this.OnU_RoleChanging(value);
					this.SendPropertyChanging();
					this._U_Role = value;
					this.SendPropertyChanged("U_Role");
					this.OnU_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_CanDelete", DbType="Bit")]
		public System.Nullable<bool> U_CanDelete
		{
			get
			{
				return this._U_CanDelete;
			}
			set
			{
				if ((this._U_CanDelete != value))
				{
					this.OnU_CanDeleteChanging(value);
					this.SendPropertyChanging();
					this._U_CanDelete = value;
					this.SendPropertyChanged("U_CanDelete");
					this.OnU_CanDeleteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shops")]
	public partial class Shops : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _S_ID;
		
		private string _S_Name;
		
		private System.Nullable<int> _S_Category;
		
		private string _S_ContactName;
		
		private string _S_ContactTel;
		
		private string _S_Address;
		
		private string _S_Remark;
		
		private System.Nullable<bool> _S_IsHasSetAdmin;
		
		private System.Nullable<System.DateTime> _S_CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IDChanging(int value);
    partial void OnS_IDChanged();
    partial void OnS_NameChanging(string value);
    partial void OnS_NameChanged();
    partial void OnS_CategoryChanging(System.Nullable<int> value);
    partial void OnS_CategoryChanged();
    partial void OnS_ContactNameChanging(string value);
    partial void OnS_ContactNameChanged();
    partial void OnS_ContactTelChanging(string value);
    partial void OnS_ContactTelChanged();
    partial void OnS_AddressChanging(string value);
    partial void OnS_AddressChanged();
    partial void OnS_RemarkChanging(string value);
    partial void OnS_RemarkChanged();
    partial void OnS_IsHasSetAdminChanging(System.Nullable<bool> value);
    partial void OnS_IsHasSetAdminChanged();
    partial void OnS_CreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnS_CreateTimeChanged();
    #endregion
		
		public Shops()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Name", DbType="VarChar(20)")]
		public string S_Name
		{
			get
			{
				return this._S_Name;
			}
			set
			{
				if ((this._S_Name != value))
				{
					this.OnS_NameChanging(value);
					this.SendPropertyChanging();
					this._S_Name = value;
					this.SendPropertyChanged("S_Name");
					this.OnS_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Category", DbType="Int")]
		public System.Nullable<int> S_Category
		{
			get
			{
				return this._S_Category;
			}
			set
			{
				if ((this._S_Category != value))
				{
					this.OnS_CategoryChanging(value);
					this.SendPropertyChanging();
					this._S_Category = value;
					this.SendPropertyChanged("S_Category");
					this.OnS_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ContactName", DbType="VarChar(20)")]
		public string S_ContactName
		{
			get
			{
				return this._S_ContactName;
			}
			set
			{
				if ((this._S_ContactName != value))
				{
					this.OnS_ContactNameChanging(value);
					this.SendPropertyChanging();
					this._S_ContactName = value;
					this.SendPropertyChanged("S_ContactName");
					this.OnS_ContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ContactTel", DbType="VarChar(20)")]
		public string S_ContactTel
		{
			get
			{
				return this._S_ContactTel;
			}
			set
			{
				if ((this._S_ContactTel != value))
				{
					this.OnS_ContactTelChanging(value);
					this.SendPropertyChanging();
					this._S_ContactTel = value;
					this.SendPropertyChanged("S_ContactTel");
					this.OnS_ContactTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Address", DbType="VarChar(50)")]
		public string S_Address
		{
			get
			{
				return this._S_Address;
			}
			set
			{
				if ((this._S_Address != value))
				{
					this.OnS_AddressChanging(value);
					this.SendPropertyChanging();
					this._S_Address = value;
					this.SendPropertyChanged("S_Address");
					this.OnS_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Remark", DbType="VarChar(100)")]
		public string S_Remark
		{
			get
			{
				return this._S_Remark;
			}
			set
			{
				if ((this._S_Remark != value))
				{
					this.OnS_RemarkChanging(value);
					this.SendPropertyChanging();
					this._S_Remark = value;
					this.SendPropertyChanged("S_Remark");
					this.OnS_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_IsHasSetAdmin", DbType="Bit")]
		public System.Nullable<bool> S_IsHasSetAdmin
		{
			get
			{
				return this._S_IsHasSetAdmin;
			}
			set
			{
				if ((this._S_IsHasSetAdmin != value))
				{
					this.OnS_IsHasSetAdminChanging(value);
					this.SendPropertyChanging();
					this._S_IsHasSetAdmin = value;
					this.SendPropertyChanged("S_IsHasSetAdmin");
					this.OnS_IsHasSetAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> S_CreateTime
		{
			get
			{
				return this._S_CreateTime;
			}
			set
			{
				if ((this._S_CreateTime != value))
				{
					this.OnS_CreateTimeChanging(value);
					this.SendPropertyChanging();
					this._S_CreateTime = value;
					this.SendPropertyChanged("S_CreateTime");
					this.OnS_CreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CategoryItems")]
	public partial class CategoryItems
	{
		
		private string _C_Category;
		
		private System.Nullable<int> _CI_ID;
		
		private string _CI_Name;
		
		public CategoryItems()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Category", DbType="VarChar(20)")]
		public string C_Category
		{
			get
			{
				return this._C_Category;
			}
			set
			{
				if ((this._C_Category != value))
				{
					this._C_Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI_ID", DbType="Int")]
		public System.Nullable<int> CI_ID
		{
			get
			{
				return this._CI_ID;
			}
			set
			{
				if ((this._CI_ID != value))
				{
					this._CI_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CI_Name", DbType="VarChar(20)")]
		public string CI_Name
		{
			get
			{
				return this._CI_Name;
			}
			set
			{
				if ((this._CI_Name != value))
				{
					this._CI_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CardLevels")]
	public partial class CardLevels : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CL_ID;
		
		private string _CL_LevelName;
		
		private string _CL_NeedPoint;
		
		private System.Nullable<double> _CL_Point;
		
		private System.Nullable<double> _CL_Percent;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCL_IDChanging(int value);
    partial void OnCL_IDChanged();
    partial void OnCL_LevelNameChanging(string value);
    partial void OnCL_LevelNameChanged();
    partial void OnCL_NeedPointChanging(string value);
    partial void OnCL_NeedPointChanged();
    partial void OnCL_PointChanging(System.Nullable<double> value);
    partial void OnCL_PointChanged();
    partial void OnCL_PercentChanging(System.Nullable<double> value);
    partial void OnCL_PercentChanged();
    #endregion
		
		public CardLevels()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CL_ID
		{
			get
			{
				return this._CL_ID;
			}
			set
			{
				if ((this._CL_ID != value))
				{
					this.OnCL_IDChanging(value);
					this.SendPropertyChanging();
					this._CL_ID = value;
					this.SendPropertyChanged("CL_ID");
					this.OnCL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_LevelName", DbType="NVarChar(20)")]
		public string CL_LevelName
		{
			get
			{
				return this._CL_LevelName;
			}
			set
			{
				if ((this._CL_LevelName != value))
				{
					this.OnCL_LevelNameChanging(value);
					this.SendPropertyChanging();
					this._CL_LevelName = value;
					this.SendPropertyChanged("CL_LevelName");
					this.OnCL_LevelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_NeedPoint", DbType="NVarChar(50)")]
		public string CL_NeedPoint
		{
			get
			{
				return this._CL_NeedPoint;
			}
			set
			{
				if ((this._CL_NeedPoint != value))
				{
					this.OnCL_NeedPointChanging(value);
					this.SendPropertyChanging();
					this._CL_NeedPoint = value;
					this.SendPropertyChanged("CL_NeedPoint");
					this.OnCL_NeedPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_Point", DbType="Float")]
		public System.Nullable<double> CL_Point
		{
			get
			{
				return this._CL_Point;
			}
			set
			{
				if ((this._CL_Point != value))
				{
					this.OnCL_PointChanging(value);
					this.SendPropertyChanging();
					this._CL_Point = value;
					this.SendPropertyChanged("CL_Point");
					this.OnCL_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_Percent", DbType="Float")]
		public System.Nullable<double> CL_Percent
		{
			get
			{
				return this._CL_Percent;
			}
			set
			{
				if ((this._CL_Percent != value))
				{
					this.OnCL_PercentChanging(value);
					this.SendPropertyChanging();
					this._CL_Percent = value;
					this.SendPropertyChanged("CL_Percent");
					this.OnCL_PercentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Categories : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _C_Category;
		
		private string _C_Illustration;
		
		private System.Nullable<bool> _C_IsShow;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_CategoryChanging(string value);
    partial void OnC_CategoryChanged();
    partial void OnC_IllustrationChanging(string value);
    partial void OnC_IllustrationChanged();
    partial void OnC_IsShowChanging(System.Nullable<bool> value);
    partial void OnC_IsShowChanged();
    #endregion
		
		public Categories()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Category", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string C_Category
		{
			get
			{
				return this._C_Category;
			}
			set
			{
				if ((this._C_Category != value))
				{
					this.OnC_CategoryChanging(value);
					this.SendPropertyChanging();
					this._C_Category = value;
					this.SendPropertyChanged("C_Category");
					this.OnC_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Illustration", DbType="VarChar(20)")]
		public string C_Illustration
		{
			get
			{
				return this._C_Illustration;
			}
			set
			{
				if ((this._C_Illustration != value))
				{
					this.OnC_IllustrationChanging(value);
					this.SendPropertyChanging();
					this._C_Illustration = value;
					this.SendPropertyChanged("C_Illustration");
					this.OnC_IllustrationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_IsShow", DbType="Bit")]
		public System.Nullable<bool> C_IsShow
		{
			get
			{
				return this._C_IsShow;
			}
			set
			{
				if ((this._C_IsShow != value))
				{
					this.OnC_IsShowChanging(value);
					this.SendPropertyChanging();
					this._C_IsShow = value;
					this.SendPropertyChanged("C_IsShow");
					this.OnC_IsShowChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConsumeOrders")]
	public partial class ConsumeOrders : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CO_ID;
		
		private System.Nullable<int> _S_ID;
		
		private System.Nullable<int> _U_ID;
		
		private string _CO_OrderCode;
		
		private System.Nullable<byte> _CO_OrderType;
		
		private System.Nullable<int> _MC_ID;
		
		private string _MC_CardID;
		
		private System.Nullable<int> _EG_ID;
		
		private System.Nullable<decimal> _CO_TotalMoney;
		
		private System.Nullable<decimal> _CO_DiscountMoney;
		
		private System.Nullable<int> _CO_GavePoint;
		
		private System.Nullable<decimal> _CO_Recash;
		
		private string _CO_Remark;
		
		private System.Nullable<System.DateTime> _CO_CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCO_IDChanging(int value);
    partial void OnCO_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnU_IDChanging(System.Nullable<int> value);
    partial void OnU_IDChanged();
    partial void OnCO_OrderCodeChanging(string value);
    partial void OnCO_OrderCodeChanged();
    partial void OnCO_OrderTypeChanging(System.Nullable<byte> value);
    partial void OnCO_OrderTypeChanged();
    partial void OnMC_IDChanging(System.Nullable<int> value);
    partial void OnMC_IDChanged();
    partial void OnMC_CardIDChanging(string value);
    partial void OnMC_CardIDChanged();
    partial void OnEG_IDChanging(System.Nullable<int> value);
    partial void OnEG_IDChanged();
    partial void OnCO_TotalMoneyChanging(System.Nullable<decimal> value);
    partial void OnCO_TotalMoneyChanged();
    partial void OnCO_DiscountMoneyChanging(System.Nullable<decimal> value);
    partial void OnCO_DiscountMoneyChanged();
    partial void OnCO_GavePointChanging(System.Nullable<int> value);
    partial void OnCO_GavePointChanged();
    partial void OnCO_RecashChanging(System.Nullable<decimal> value);
    partial void OnCO_RecashChanged();
    partial void OnCO_RemarkChanging(string value);
    partial void OnCO_RemarkChanged();
    partial void OnCO_CreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCO_CreateTimeChanged();
    #endregion
		
		public ConsumeOrders()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CO_ID
		{
			get
			{
				return this._CO_ID;
			}
			set
			{
				if ((this._CO_ID != value))
				{
					this.OnCO_IDChanging(value);
					this.SendPropertyChanging();
					this._CO_ID = value;
					this.SendPropertyChanged("CO_ID");
					this.OnCO_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_ID", DbType="Int")]
		public System.Nullable<int> U_ID
		{
			get
			{
				return this._U_ID;
			}
			set
			{
				if ((this._U_ID != value))
				{
					this.OnU_IDChanging(value);
					this.SendPropertyChanging();
					this._U_ID = value;
					this.SendPropertyChanged("U_ID");
					this.OnU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_OrderCode", DbType="NVarChar(20)")]
		public string CO_OrderCode
		{
			get
			{
				return this._CO_OrderCode;
			}
			set
			{
				if ((this._CO_OrderCode != value))
				{
					this.OnCO_OrderCodeChanging(value);
					this.SendPropertyChanging();
					this._CO_OrderCode = value;
					this.SendPropertyChanged("CO_OrderCode");
					this.OnCO_OrderCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_OrderType", DbType="TinyInt")]
		public System.Nullable<byte> CO_OrderType
		{
			get
			{
				return this._CO_OrderType;
			}
			set
			{
				if ((this._CO_OrderType != value))
				{
					this.OnCO_OrderTypeChanging(value);
					this.SendPropertyChanging();
					this._CO_OrderType = value;
					this.SendPropertyChanged("CO_OrderType");
					this.OnCO_OrderTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_ID", DbType="Int")]
		public System.Nullable<int> MC_ID
		{
			get
			{
				return this._MC_ID;
			}
			set
			{
				if ((this._MC_ID != value))
				{
					this.OnMC_IDChanging(value);
					this.SendPropertyChanging();
					this._MC_ID = value;
					this.SendPropertyChanged("MC_ID");
					this.OnMC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_CardID", DbType="NVarChar(50)")]
		public string MC_CardID
		{
			get
			{
				return this._MC_CardID;
			}
			set
			{
				if ((this._MC_CardID != value))
				{
					this.OnMC_CardIDChanging(value);
					this.SendPropertyChanging();
					this._MC_CardID = value;
					this.SendPropertyChanged("MC_CardID");
					this.OnMC_CardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_ID", DbType="Int")]
		public System.Nullable<int> EG_ID
		{
			get
			{
				return this._EG_ID;
			}
			set
			{
				if ((this._EG_ID != value))
				{
					this.OnEG_IDChanging(value);
					this.SendPropertyChanging();
					this._EG_ID = value;
					this.SendPropertyChanged("EG_ID");
					this.OnEG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_TotalMoney", DbType="Money")]
		public System.Nullable<decimal> CO_TotalMoney
		{
			get
			{
				return this._CO_TotalMoney;
			}
			set
			{
				if ((this._CO_TotalMoney != value))
				{
					this.OnCO_TotalMoneyChanging(value);
					this.SendPropertyChanging();
					this._CO_TotalMoney = value;
					this.SendPropertyChanged("CO_TotalMoney");
					this.OnCO_TotalMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_DiscountMoney", DbType="Money")]
		public System.Nullable<decimal> CO_DiscountMoney
		{
			get
			{
				return this._CO_DiscountMoney;
			}
			set
			{
				if ((this._CO_DiscountMoney != value))
				{
					this.OnCO_DiscountMoneyChanging(value);
					this.SendPropertyChanging();
					this._CO_DiscountMoney = value;
					this.SendPropertyChanged("CO_DiscountMoney");
					this.OnCO_DiscountMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_GavePoint", DbType="Int")]
		public System.Nullable<int> CO_GavePoint
		{
			get
			{
				return this._CO_GavePoint;
			}
			set
			{
				if ((this._CO_GavePoint != value))
				{
					this.OnCO_GavePointChanging(value);
					this.SendPropertyChanging();
					this._CO_GavePoint = value;
					this.SendPropertyChanged("CO_GavePoint");
					this.OnCO_GavePointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_Recash", DbType="Money")]
		public System.Nullable<decimal> CO_Recash
		{
			get
			{
				return this._CO_Recash;
			}
			set
			{
				if ((this._CO_Recash != value))
				{
					this.OnCO_RecashChanging(value);
					this.SendPropertyChanging();
					this._CO_Recash = value;
					this.SendPropertyChanged("CO_Recash");
					this.OnCO_RecashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_Remark", DbType="VarChar(255)")]
		public string CO_Remark
		{
			get
			{
				return this._CO_Remark;
			}
			set
			{
				if ((this._CO_Remark != value))
				{
					this.OnCO_RemarkChanging(value);
					this.SendPropertyChanging();
					this._CO_Remark = value;
					this.SendPropertyChanged("CO_Remark");
					this.OnCO_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CO_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CO_CreateTime
		{
			get
			{
				return this._CO_CreateTime;
			}
			set
			{
				if ((this._CO_CreateTime != value))
				{
					this.OnCO_CreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CO_CreateTime = value;
					this.SendPropertyChanged("CO_CreateTime");
					this.OnCO_CreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExchangGifts")]
	public partial class ExchangGifts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EG_ID;
		
		private System.Nullable<int> _S_ID;
		
		private string _EG_GiftCode;
		
		private string _EG_GiftName;
		
		private string _EG_Photo;
		
		private System.Nullable<int> _EG_Point;
		
		private System.Nullable<int> _EG_Number;
		
		private System.Nullable<int> _EG_ExchangNum;
		
		private string _EG_Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEG_IDChanging(int value);
    partial void OnEG_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnEG_GiftCodeChanging(string value);
    partial void OnEG_GiftCodeChanged();
    partial void OnEG_GiftNameChanging(string value);
    partial void OnEG_GiftNameChanged();
    partial void OnEG_PhotoChanging(string value);
    partial void OnEG_PhotoChanged();
    partial void OnEG_PointChanging(System.Nullable<int> value);
    partial void OnEG_PointChanged();
    partial void OnEG_NumberChanging(System.Nullable<int> value);
    partial void OnEG_NumberChanged();
    partial void OnEG_ExchangNumChanging(System.Nullable<int> value);
    partial void OnEG_ExchangNumChanged();
    partial void OnEG_RemarkChanging(string value);
    partial void OnEG_RemarkChanged();
    #endregion
		
		public ExchangGifts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EG_ID
		{
			get
			{
				return this._EG_ID;
			}
			set
			{
				if ((this._EG_ID != value))
				{
					this.OnEG_IDChanging(value);
					this.SendPropertyChanging();
					this._EG_ID = value;
					this.SendPropertyChanged("EG_ID");
					this.OnEG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_GiftCode", DbType="VarChar(255)")]
		public string EG_GiftCode
		{
			get
			{
				return this._EG_GiftCode;
			}
			set
			{
				if ((this._EG_GiftCode != value))
				{
					this.OnEG_GiftCodeChanging(value);
					this.SendPropertyChanging();
					this._EG_GiftCode = value;
					this.SendPropertyChanged("EG_GiftCode");
					this.OnEG_GiftCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_GiftName", DbType="VarChar(255)")]
		public string EG_GiftName
		{
			get
			{
				return this._EG_GiftName;
			}
			set
			{
				if ((this._EG_GiftName != value))
				{
					this.OnEG_GiftNameChanging(value);
					this.SendPropertyChanging();
					this._EG_GiftName = value;
					this.SendPropertyChanged("EG_GiftName");
					this.OnEG_GiftNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_Photo", DbType="VarChar(255)")]
		public string EG_Photo
		{
			get
			{
				return this._EG_Photo;
			}
			set
			{
				if ((this._EG_Photo != value))
				{
					this.OnEG_PhotoChanging(value);
					this.SendPropertyChanging();
					this._EG_Photo = value;
					this.SendPropertyChanged("EG_Photo");
					this.OnEG_PhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_Point", DbType="Int")]
		public System.Nullable<int> EG_Point
		{
			get
			{
				return this._EG_Point;
			}
			set
			{
				if ((this._EG_Point != value))
				{
					this.OnEG_PointChanging(value);
					this.SendPropertyChanging();
					this._EG_Point = value;
					this.SendPropertyChanged("EG_Point");
					this.OnEG_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_Number", DbType="Int")]
		public System.Nullable<int> EG_Number
		{
			get
			{
				return this._EG_Number;
			}
			set
			{
				if ((this._EG_Number != value))
				{
					this.OnEG_NumberChanging(value);
					this.SendPropertyChanging();
					this._EG_Number = value;
					this.SendPropertyChanged("EG_Number");
					this.OnEG_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_ExchangNum", DbType="Int")]
		public System.Nullable<int> EG_ExchangNum
		{
			get
			{
				return this._EG_ExchangNum;
			}
			set
			{
				if ((this._EG_ExchangNum != value))
				{
					this.OnEG_ExchangNumChanging(value);
					this.SendPropertyChanging();
					this._EG_ExchangNum = value;
					this.SendPropertyChanged("EG_ExchangNum");
					this.OnEG_ExchangNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_Remark", DbType="VarChar(255)")]
		public string EG_Remark
		{
			get
			{
				return this._EG_Remark;
			}
			set
			{
				if ((this._EG_Remark != value))
				{
					this.OnEG_RemarkChanging(value);
					this.SendPropertyChanging();
					this._EG_Remark = value;
					this.SendPropertyChanged("EG_Remark");
					this.OnEG_RemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExchangLogs")]
	public partial class ExchangLogs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EL_ID;
		
		private System.Nullable<int> _S_ID;
		
		private System.Nullable<int> _U_ID;
		
		private System.Nullable<int> _MC_ID;
		
		private string _MC_CardID;
		
		private string _MC_Name;
		
		private System.Nullable<int> _EG_ID;
		
		private string _EG_GiftCode;
		
		private string _EG_GiftName;
		
		private System.Nullable<int> _EL_Number;
		
		private System.Nullable<int> _EL_Point;
		
		private System.Nullable<System.DateTime> _EL_CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEL_IDChanging(int value);
    partial void OnEL_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnU_IDChanging(System.Nullable<int> value);
    partial void OnU_IDChanged();
    partial void OnMC_IDChanging(System.Nullable<int> value);
    partial void OnMC_IDChanged();
    partial void OnMC_CardIDChanging(string value);
    partial void OnMC_CardIDChanged();
    partial void OnMC_NameChanging(string value);
    partial void OnMC_NameChanged();
    partial void OnEG_IDChanging(System.Nullable<int> value);
    partial void OnEG_IDChanged();
    partial void OnEG_GiftCodeChanging(string value);
    partial void OnEG_GiftCodeChanged();
    partial void OnEG_GiftNameChanging(string value);
    partial void OnEG_GiftNameChanged();
    partial void OnEL_NumberChanging(System.Nullable<int> value);
    partial void OnEL_NumberChanged();
    partial void OnEL_PointChanging(System.Nullable<int> value);
    partial void OnEL_PointChanged();
    partial void OnEL_CreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEL_CreateTimeChanged();
    #endregion
		
		public ExchangLogs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EL_ID
		{
			get
			{
				return this._EL_ID;
			}
			set
			{
				if ((this._EL_ID != value))
				{
					this.OnEL_IDChanging(value);
					this.SendPropertyChanging();
					this._EL_ID = value;
					this.SendPropertyChanged("EL_ID");
					this.OnEL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_ID", DbType="Int")]
		public System.Nullable<int> U_ID
		{
			get
			{
				return this._U_ID;
			}
			set
			{
				if ((this._U_ID != value))
				{
					this.OnU_IDChanging(value);
					this.SendPropertyChanging();
					this._U_ID = value;
					this.SendPropertyChanged("U_ID");
					this.OnU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_ID", DbType="Int")]
		public System.Nullable<int> MC_ID
		{
			get
			{
				return this._MC_ID;
			}
			set
			{
				if ((this._MC_ID != value))
				{
					this.OnMC_IDChanging(value);
					this.SendPropertyChanging();
					this._MC_ID = value;
					this.SendPropertyChanged("MC_ID");
					this.OnMC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_CardID", DbType="NVarChar(50)")]
		public string MC_CardID
		{
			get
			{
				return this._MC_CardID;
			}
			set
			{
				if ((this._MC_CardID != value))
				{
					this.OnMC_CardIDChanging(value);
					this.SendPropertyChanging();
					this._MC_CardID = value;
					this.SendPropertyChanged("MC_CardID");
					this.OnMC_CardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Name", DbType="NVarChar(20)")]
		public string MC_Name
		{
			get
			{
				return this._MC_Name;
			}
			set
			{
				if ((this._MC_Name != value))
				{
					this.OnMC_NameChanging(value);
					this.SendPropertyChanging();
					this._MC_Name = value;
					this.SendPropertyChanged("MC_Name");
					this.OnMC_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_ID", DbType="Int")]
		public System.Nullable<int> EG_ID
		{
			get
			{
				return this._EG_ID;
			}
			set
			{
				if ((this._EG_ID != value))
				{
					this.OnEG_IDChanging(value);
					this.SendPropertyChanging();
					this._EG_ID = value;
					this.SendPropertyChanged("EG_ID");
					this.OnEG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_GiftCode", DbType="NVarChar(50)")]
		public string EG_GiftCode
		{
			get
			{
				return this._EG_GiftCode;
			}
			set
			{
				if ((this._EG_GiftCode != value))
				{
					this.OnEG_GiftCodeChanging(value);
					this.SendPropertyChanging();
					this._EG_GiftCode = value;
					this.SendPropertyChanged("EG_GiftCode");
					this.OnEG_GiftCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EG_GiftName", DbType="NVarChar(50)")]
		public string EG_GiftName
		{
			get
			{
				return this._EG_GiftName;
			}
			set
			{
				if ((this._EG_GiftName != value))
				{
					this.OnEG_GiftNameChanging(value);
					this.SendPropertyChanging();
					this._EG_GiftName = value;
					this.SendPropertyChanged("EG_GiftName");
					this.OnEG_GiftNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EL_Number", DbType="Int")]
		public System.Nullable<int> EL_Number
		{
			get
			{
				return this._EL_Number;
			}
			set
			{
				if ((this._EL_Number != value))
				{
					this.OnEL_NumberChanging(value);
					this.SendPropertyChanging();
					this._EL_Number = value;
					this.SendPropertyChanged("EL_Number");
					this.OnEL_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EL_Point", DbType="Int")]
		public System.Nullable<int> EL_Point
		{
			get
			{
				return this._EL_Point;
			}
			set
			{
				if ((this._EL_Point != value))
				{
					this.OnEL_PointChanging(value);
					this.SendPropertyChanging();
					this._EL_Point = value;
					this.SendPropertyChanged("EL_Point");
					this.OnEL_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EL_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EL_CreateTime
		{
			get
			{
				return this._EL_CreateTime;
			}
			set
			{
				if ((this._EL_CreateTime != value))
				{
					this.OnEL_CreateTimeChanging(value);
					this.SendPropertyChanging();
					this._EL_CreateTime = value;
					this.SendPropertyChanged("EL_CreateTime");
					this.OnEL_CreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransferLogs")]
	public partial class TransferLogs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TL_ID;
		
		private System.Nullable<int> _S_ID;
		
		private System.Nullable<int> _U_ID;
		
		private System.Nullable<int> _TL_FromMC_ID;
		
		private string _TL_FromMC_CardID;
		
		private System.Nullable<int> _TL_ToMC_ID;
		
		private string _TL_ToMC_CardID;
		
		private System.Nullable<decimal> _TL_TransferMoney;
		
		private string _TL_Remark;
		
		private System.Nullable<System.DateTime> _TL_CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTL_IDChanging(int value);
    partial void OnTL_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnU_IDChanging(System.Nullable<int> value);
    partial void OnU_IDChanged();
    partial void OnTL_FromMC_IDChanging(System.Nullable<int> value);
    partial void OnTL_FromMC_IDChanged();
    partial void OnTL_FromMC_CardIDChanging(string value);
    partial void OnTL_FromMC_CardIDChanged();
    partial void OnTL_ToMC_IDChanging(System.Nullable<int> value);
    partial void OnTL_ToMC_IDChanged();
    partial void OnTL_ToMC_CardIDChanging(string value);
    partial void OnTL_ToMC_CardIDChanged();
    partial void OnTL_TransferMoneyChanging(System.Nullable<decimal> value);
    partial void OnTL_TransferMoneyChanged();
    partial void OnTL_RemarkChanging(string value);
    partial void OnTL_RemarkChanged();
    partial void OnTL_CreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnTL_CreateTimeChanged();
    #endregion
		
		public TransferLogs()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TL_ID
		{
			get
			{
				return this._TL_ID;
			}
			set
			{
				if ((this._TL_ID != value))
				{
					this.OnTL_IDChanging(value);
					this.SendPropertyChanging();
					this._TL_ID = value;
					this.SendPropertyChanged("TL_ID");
					this.OnTL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_ID", DbType="Int")]
		public System.Nullable<int> U_ID
		{
			get
			{
				return this._U_ID;
			}
			set
			{
				if ((this._U_ID != value))
				{
					this.OnU_IDChanging(value);
					this.SendPropertyChanging();
					this._U_ID = value;
					this.SendPropertyChanged("U_ID");
					this.OnU_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_FromMC_ID", DbType="Int")]
		public System.Nullable<int> TL_FromMC_ID
		{
			get
			{
				return this._TL_FromMC_ID;
			}
			set
			{
				if ((this._TL_FromMC_ID != value))
				{
					this.OnTL_FromMC_IDChanging(value);
					this.SendPropertyChanging();
					this._TL_FromMC_ID = value;
					this.SendPropertyChanged("TL_FromMC_ID");
					this.OnTL_FromMC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_FromMC_CardID", DbType="NVarChar(50)")]
		public string TL_FromMC_CardID
		{
			get
			{
				return this._TL_FromMC_CardID;
			}
			set
			{
				if ((this._TL_FromMC_CardID != value))
				{
					this.OnTL_FromMC_CardIDChanging(value);
					this.SendPropertyChanging();
					this._TL_FromMC_CardID = value;
					this.SendPropertyChanged("TL_FromMC_CardID");
					this.OnTL_FromMC_CardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ToMC_ID", DbType="Int")]
		public System.Nullable<int> TL_ToMC_ID
		{
			get
			{
				return this._TL_ToMC_ID;
			}
			set
			{
				if ((this._TL_ToMC_ID != value))
				{
					this.OnTL_ToMC_IDChanging(value);
					this.SendPropertyChanging();
					this._TL_ToMC_ID = value;
					this.SendPropertyChanged("TL_ToMC_ID");
					this.OnTL_ToMC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_ToMC_CardID", DbType="NVarChar(50)")]
		public string TL_ToMC_CardID
		{
			get
			{
				return this._TL_ToMC_CardID;
			}
			set
			{
				if ((this._TL_ToMC_CardID != value))
				{
					this.OnTL_ToMC_CardIDChanging(value);
					this.SendPropertyChanging();
					this._TL_ToMC_CardID = value;
					this.SendPropertyChanged("TL_ToMC_CardID");
					this.OnTL_ToMC_CardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_TransferMoney", DbType="Money")]
		public System.Nullable<decimal> TL_TransferMoney
		{
			get
			{
				return this._TL_TransferMoney;
			}
			set
			{
				if ((this._TL_TransferMoney != value))
				{
					this.OnTL_TransferMoneyChanging(value);
					this.SendPropertyChanging();
					this._TL_TransferMoney = value;
					this.SendPropertyChanged("TL_TransferMoney");
					this.OnTL_TransferMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_Remark", DbType="VarChar(200)")]
		public string TL_Remark
		{
			get
			{
				return this._TL_Remark;
			}
			set
			{
				if ((this._TL_Remark != value))
				{
					this.OnTL_RemarkChanging(value);
					this.SendPropertyChanging();
					this._TL_Remark = value;
					this.SendPropertyChanged("TL_Remark");
					this.OnTL_RemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> TL_CreateTime
		{
			get
			{
				return this._TL_CreateTime;
			}
			set
			{
				if ((this._TL_CreateTime != value))
				{
					this.OnTL_CreateTimeChanging(value);
					this.SendPropertyChanging();
					this._TL_CreateTime = value;
					this.SendPropertyChanged("TL_CreateTime");
					this.OnTL_CreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MemCards")]
	public partial class MemCards : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MC_ID;
		
		private System.Nullable<int> _CL_ID;
		
		private System.Nullable<int> _S_ID;
		
		private string _MC_CardID;
		
		private string _MC_Password;
		
		private string _MC_Name;
		
		private System.Nullable<bool> _MC_Sex;
		
		private string _MC_Mobile;
		
		private string _MC_Photo;
		
		private System.Nullable<int> _MC_Birthday_Month;
		
		private System.Nullable<int> _MC_Birthday_Day;
		
		private System.Nullable<bool> _MC_BirthdayType;
		
		private System.Nullable<bool> _MC_IsPast;
		
		private System.Nullable<System.DateTime> _MC_PastTime;
		
		private System.Nullable<int> _MC_Point;
		
		private System.Nullable<float> _MC_Money;
		
		private System.Nullable<float> _MC_TotalMoney;
		
		private System.Nullable<int> _MC_TotalCount;
		
		private System.Nullable<int> _MC_State;
		
		private System.Nullable<bool> _MC_IsPointAuto;
		
		private System.Nullable<int> _MC_RefererID;
		
		private string _MC_RefererCard;
		
		private string _MC_RefererName;
		
		private System.Nullable<System.DateTime> _MC_CreateTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMC_IDChanging(int value);
    partial void OnMC_IDChanged();
    partial void OnCL_IDChanging(System.Nullable<int> value);
    partial void OnCL_IDChanged();
    partial void OnS_IDChanging(System.Nullable<int> value);
    partial void OnS_IDChanged();
    partial void OnMC_CardIDChanging(string value);
    partial void OnMC_CardIDChanged();
    partial void OnMC_PasswordChanging(string value);
    partial void OnMC_PasswordChanged();
    partial void OnMC_NameChanging(string value);
    partial void OnMC_NameChanged();
    partial void OnMC_SexChanging(System.Nullable<bool> value);
    partial void OnMC_SexChanged();
    partial void OnMC_MobileChanging(string value);
    partial void OnMC_MobileChanged();
    partial void OnMC_PhotoChanging(string value);
    partial void OnMC_PhotoChanged();
    partial void OnMC_Birthday_MonthChanging(System.Nullable<int> value);
    partial void OnMC_Birthday_MonthChanged();
    partial void OnMC_Birthday_DayChanging(System.Nullable<int> value);
    partial void OnMC_Birthday_DayChanged();
    partial void OnMC_BirthdayTypeChanging(System.Nullable<bool> value);
    partial void OnMC_BirthdayTypeChanged();
    partial void OnMC_IsPastChanging(System.Nullable<bool> value);
    partial void OnMC_IsPastChanged();
    partial void OnMC_PastTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMC_PastTimeChanged();
    partial void OnMC_PointChanging(System.Nullable<int> value);
    partial void OnMC_PointChanged();
    partial void OnMC_MoneyChanging(System.Nullable<float> value);
    partial void OnMC_MoneyChanged();
    partial void OnMC_TotalMoneyChanging(System.Nullable<float> value);
    partial void OnMC_TotalMoneyChanged();
    partial void OnMC_TotalCountChanging(System.Nullable<int> value);
    partial void OnMC_TotalCountChanged();
    partial void OnMC_StateChanging(System.Nullable<int> value);
    partial void OnMC_StateChanged();
    partial void OnMC_IsPointAutoChanging(System.Nullable<bool> value);
    partial void OnMC_IsPointAutoChanged();
    partial void OnMC_RefererIDChanging(System.Nullable<int> value);
    partial void OnMC_RefererIDChanged();
    partial void OnMC_RefererCardChanging(string value);
    partial void OnMC_RefererCardChanged();
    partial void OnMC_RefererNameChanging(string value);
    partial void OnMC_RefererNameChanged();
    partial void OnMC_CreateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMC_CreateTimeChanged();
    #endregion
		
		public MemCards()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MC_ID
		{
			get
			{
				return this._MC_ID;
			}
			set
			{
				if ((this._MC_ID != value))
				{
					this.OnMC_IDChanging(value);
					this.SendPropertyChanging();
					this._MC_ID = value;
					this.SendPropertyChanged("MC_ID");
					this.OnMC_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CL_ID", DbType="Int")]
		public System.Nullable<int> CL_ID
		{
			get
			{
				return this._CL_ID;
			}
			set
			{
				if ((this._CL_ID != value))
				{
					this.OnCL_IDChanging(value);
					this.SendPropertyChanging();
					this._CL_ID = value;
					this.SendPropertyChanged("CL_ID");
					this.OnCL_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", DbType="Int")]
		public System.Nullable<int> S_ID
		{
			get
			{
				return this._S_ID;
			}
			set
			{
				if ((this._S_ID != value))
				{
					this.OnS_IDChanging(value);
					this.SendPropertyChanging();
					this._S_ID = value;
					this.SendPropertyChanged("S_ID");
					this.OnS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_CardID", DbType="NVarChar(50)")]
		public string MC_CardID
		{
			get
			{
				return this._MC_CardID;
			}
			set
			{
				if ((this._MC_CardID != value))
				{
					this.OnMC_CardIDChanging(value);
					this.SendPropertyChanging();
					this._MC_CardID = value;
					this.SendPropertyChanged("MC_CardID");
					this.OnMC_CardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Password", DbType="NVarChar(20)")]
		public string MC_Password
		{
			get
			{
				return this._MC_Password;
			}
			set
			{
				if ((this._MC_Password != value))
				{
					this.OnMC_PasswordChanging(value);
					this.SendPropertyChanging();
					this._MC_Password = value;
					this.SendPropertyChanged("MC_Password");
					this.OnMC_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Name", DbType="NVarChar(20)")]
		public string MC_Name
		{
			get
			{
				return this._MC_Name;
			}
			set
			{
				if ((this._MC_Name != value))
				{
					this.OnMC_NameChanging(value);
					this.SendPropertyChanging();
					this._MC_Name = value;
					this.SendPropertyChanged("MC_Name");
					this.OnMC_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Sex", DbType="Bit")]
		public System.Nullable<bool> MC_Sex
		{
			get
			{
				return this._MC_Sex;
			}
			set
			{
				if ((this._MC_Sex != value))
				{
					this.OnMC_SexChanging(value);
					this.SendPropertyChanging();
					this._MC_Sex = value;
					this.SendPropertyChanged("MC_Sex");
					this.OnMC_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Mobile", DbType="NVarChar(50)")]
		public string MC_Mobile
		{
			get
			{
				return this._MC_Mobile;
			}
			set
			{
				if ((this._MC_Mobile != value))
				{
					this.OnMC_MobileChanging(value);
					this.SendPropertyChanging();
					this._MC_Mobile = value;
					this.SendPropertyChanged("MC_Mobile");
					this.OnMC_MobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Photo", DbType="VarChar(200)")]
		public string MC_Photo
		{
			get
			{
				return this._MC_Photo;
			}
			set
			{
				if ((this._MC_Photo != value))
				{
					this.OnMC_PhotoChanging(value);
					this.SendPropertyChanging();
					this._MC_Photo = value;
					this.SendPropertyChanged("MC_Photo");
					this.OnMC_PhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Birthday_Month", DbType="Int")]
		public System.Nullable<int> MC_Birthday_Month
		{
			get
			{
				return this._MC_Birthday_Month;
			}
			set
			{
				if ((this._MC_Birthday_Month != value))
				{
					this.OnMC_Birthday_MonthChanging(value);
					this.SendPropertyChanging();
					this._MC_Birthday_Month = value;
					this.SendPropertyChanged("MC_Birthday_Month");
					this.OnMC_Birthday_MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Birthday_Day", DbType="Int")]
		public System.Nullable<int> MC_Birthday_Day
		{
			get
			{
				return this._MC_Birthday_Day;
			}
			set
			{
				if ((this._MC_Birthday_Day != value))
				{
					this.OnMC_Birthday_DayChanging(value);
					this.SendPropertyChanging();
					this._MC_Birthday_Day = value;
					this.SendPropertyChanged("MC_Birthday_Day");
					this.OnMC_Birthday_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_BirthdayType", DbType="Bit")]
		public System.Nullable<bool> MC_BirthdayType
		{
			get
			{
				return this._MC_BirthdayType;
			}
			set
			{
				if ((this._MC_BirthdayType != value))
				{
					this.OnMC_BirthdayTypeChanging(value);
					this.SendPropertyChanging();
					this._MC_BirthdayType = value;
					this.SendPropertyChanged("MC_BirthdayType");
					this.OnMC_BirthdayTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_IsPast", DbType="Bit")]
		public System.Nullable<bool> MC_IsPast
		{
			get
			{
				return this._MC_IsPast;
			}
			set
			{
				if ((this._MC_IsPast != value))
				{
					this.OnMC_IsPastChanging(value);
					this.SendPropertyChanging();
					this._MC_IsPast = value;
					this.SendPropertyChanged("MC_IsPast");
					this.OnMC_IsPastChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_PastTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> MC_PastTime
		{
			get
			{
				return this._MC_PastTime;
			}
			set
			{
				if ((this._MC_PastTime != value))
				{
					this.OnMC_PastTimeChanging(value);
					this.SendPropertyChanging();
					this._MC_PastTime = value;
					this.SendPropertyChanged("MC_PastTime");
					this.OnMC_PastTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Point", DbType="Int")]
		public System.Nullable<int> MC_Point
		{
			get
			{
				return this._MC_Point;
			}
			set
			{
				if ((this._MC_Point != value))
				{
					this.OnMC_PointChanging(value);
					this.SendPropertyChanging();
					this._MC_Point = value;
					this.SendPropertyChanged("MC_Point");
					this.OnMC_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_Money", DbType="Real")]
		public System.Nullable<float> MC_Money
		{
			get
			{
				return this._MC_Money;
			}
			set
			{
				if ((this._MC_Money != value))
				{
					this.OnMC_MoneyChanging(value);
					this.SendPropertyChanging();
					this._MC_Money = value;
					this.SendPropertyChanged("MC_Money");
					this.OnMC_MoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_TotalMoney", DbType="Real")]
		public System.Nullable<float> MC_TotalMoney
		{
			get
			{
				return this._MC_TotalMoney;
			}
			set
			{
				if ((this._MC_TotalMoney != value))
				{
					this.OnMC_TotalMoneyChanging(value);
					this.SendPropertyChanging();
					this._MC_TotalMoney = value;
					this.SendPropertyChanged("MC_TotalMoney");
					this.OnMC_TotalMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_TotalCount", DbType="Int")]
		public System.Nullable<int> MC_TotalCount
		{
			get
			{
				return this._MC_TotalCount;
			}
			set
			{
				if ((this._MC_TotalCount != value))
				{
					this.OnMC_TotalCountChanging(value);
					this.SendPropertyChanging();
					this._MC_TotalCount = value;
					this.SendPropertyChanged("MC_TotalCount");
					this.OnMC_TotalCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_State", DbType="Int")]
		public System.Nullable<int> MC_State
		{
			get
			{
				return this._MC_State;
			}
			set
			{
				if ((this._MC_State != value))
				{
					this.OnMC_StateChanging(value);
					this.SendPropertyChanging();
					this._MC_State = value;
					this.SendPropertyChanged("MC_State");
					this.OnMC_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_IsPointAuto", DbType="Bit")]
		public System.Nullable<bool> MC_IsPointAuto
		{
			get
			{
				return this._MC_IsPointAuto;
			}
			set
			{
				if ((this._MC_IsPointAuto != value))
				{
					this.OnMC_IsPointAutoChanging(value);
					this.SendPropertyChanging();
					this._MC_IsPointAuto = value;
					this.SendPropertyChanged("MC_IsPointAuto");
					this.OnMC_IsPointAutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_RefererID", DbType="Int")]
		public System.Nullable<int> MC_RefererID
		{
			get
			{
				return this._MC_RefererID;
			}
			set
			{
				if ((this._MC_RefererID != value))
				{
					this.OnMC_RefererIDChanging(value);
					this.SendPropertyChanging();
					this._MC_RefererID = value;
					this.SendPropertyChanged("MC_RefererID");
					this.OnMC_RefererIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_RefererCard", DbType="NVarChar(50)")]
		public string MC_RefererCard
		{
			get
			{
				return this._MC_RefererCard;
			}
			set
			{
				if ((this._MC_RefererCard != value))
				{
					this.OnMC_RefererCardChanging(value);
					this.SendPropertyChanging();
					this._MC_RefererCard = value;
					this.SendPropertyChanged("MC_RefererCard");
					this.OnMC_RefererCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_RefererName", DbType="NVarChar(20)")]
		public string MC_RefererName
		{
			get
			{
				return this._MC_RefererName;
			}
			set
			{
				if ((this._MC_RefererName != value))
				{
					this.OnMC_RefererNameChanging(value);
					this.SendPropertyChanging();
					this._MC_RefererName = value;
					this.SendPropertyChanged("MC_RefererName");
					this.OnMC_RefererNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MC_CreateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> MC_CreateTime
		{
			get
			{
				return this._MC_CreateTime;
			}
			set
			{
				if ((this._MC_CreateTime != value))
				{
					this.OnMC_CreateTimeChanging(value);
					this.SendPropertyChanging();
					this._MC_CreateTime = value;
					this.SendPropertyChanged("MC_CreateTime");
					this.OnMC_CreateTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
